- name: Get Active User Sessions
  uri:
    url: "{{ space_api_uri }}/space/user-management/users"
    method: GET
    follow_redirects: all
    return_content: yes
    headers:
        Accept: application/vnd.net.juniper.space.user-management.users+json;version=3
        Cookie: "{{ login.set_cookie }}"
    validate_certs:  "{{ ssl_verification }}"
  register: result
