- name: Logout from Junos Space
  uri:
    url: "{{ space_api_uri }}/space/user-management/logout"
    method: POST
    status_code: 200
    validate_certs: "{{ ssl_verification }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
