#####################################################
# options:
#   policy_id:
#     description:
#       - The ID of the NAT policy for which the NAT rule should be added
#     required: true
#     type: int
#
#   rule_group_id:
#     description:
#       - The ID of the NAT Rule Group for which NAT rule should be added
#     required: true
#     type: int
#
#   rule_order:
#     description:
#       - The ID of the NAT Rule Group for which NAT rule should be added
#     required: true
#     type: int
#
#   rule_name:
#     description:
#       - The name of the NAT Rule
#     required: true
#     type: str
# 
# rule_description:
# src_address:
#     name:
#     id:
# src_zone:
# dst_address:
#     name:
#     id:
# service:
#     name:
#     id:
# dst_zone:




- name: Creating SNAT Rule
  uri:
    url: "{{ space_api_uri }}/juniper/sd/policy-management/nat/policies/{{ policy_id }}/rules"
    method: POST
    follow_redirects: all
    return_content: yes
    status_code: 200
    headers:
      Accept: application/vnd.juniper.sd.policy-management.nat.rule+json;version=2;q=0.02
      Content-Type: application/vnd.juniper.sd.policy-management.nat.rule+json;version=2;charset=UTF-8
      Cookie: "{{ login.set_cookie }}"
    body_format: json
    body: >
      {
          "rule": {
              "disabled": false,
              "edit-version": 0,
              "name": "Device-1",
              "nat-type": "SOURCE",
              "original-packet": {
                  "dst-address": {
                      "address-reference": [
                          {
                              "id": "{{ dst_address.id }}",
                              "name": "{{ dst_address.name }}"
                          }
                      ]
                  },
                  "dst-port-sets": {
                      "reference": []
                  },
                  "dst-traffic-match-type": "ZONE",
                  "dst-traffic-match-value": {
                      "dst-traffic-match-value": [
                          "{{ dst_zone }}"
                      ]
                  },
                  "dst-zone-sets": {
                      "reference": []
                  },
                  "proxy-arp-enabled": false,
                  "proxy-arp-entry": {
                      "state": "NOCHANGE"
                  },
                  "src-address": {
                      "address-reference": [
                          {
                              "id": "{{ src_address.id }}",
                              "name": "{{ src_address.name }}"
                          }
                      ]
                  },
                  "src-port-sets": {
                      "reference": []
                  },
                  "src-traffic-match-type": "ZONE",
                  "src-traffic-match-value": {
                      "src-traffic-match-value": [
                          "{{ src_zone }}"
                      ]
                  },
                  "src-zone-sets": {
                      "reference": []
                  }
              },
              "policy-id": {{ policy_id }},
              "rule-group-id": {{ rule_group_id }},
              "rule-group-type": "CUSTOM",
              "rule-order": {{ rule_count }},
              "rule-type": "RULE",
              "rulegroup-disabled": false,
              "services": {
                  "service-reference": [
                      {
                          "id": "{{ service.id }}",
                          "is-group": false,
                          "name": "{{ service.name }}"
                      }
                  ]
              },        "translated-packet": {
                  "egress-interface": {
                      "egress-interface": []
                  },
                  "mapped-port": "",
                  "persistent-nat-setting": {
                      "address-mapping": false,
                      "persistent-nat-type": "NONE"
                  },
                  "pool-addresses": {},
                  "poxy-arp-entries": {
                  },
                  "proxy-arp-enabled": false,
                  "translated-address": {},
                  "translated-traffic-match-type": "NO_TRANSLATION"
              },
              "version": 2
          }
      }
    validate_certs:  "{{ ssl_verification }}"
  register: result
