#####################################################
# returns:
#   - specific rule info
# options:
#   policy_id:
#     description:
#       - The ID of the NAT policy for which rules should be retrieved
#     required: true
#     type: int
#
# options:
#   rule_id:
#     description:
#       - The ID of the NAT Rule for which rule info should be retrieved
#       - If left blank all rules for the given policy_id are returned
#     required: true
#     type: int

- name: SD - Get NAT Rules for Policy
  uri:
    url: "{{ space_api_uri }}/juniper/sd/policy-management/nat/policies/{{ policy_id }}/rules/{{ rule_id }}"
    method: GET
    return_content: yes
    headers:
      Accept: application/vnd.juniper.sd.policy-management.nat.rule+json;version=2;q=0.02
      Cookie: "{{ login.set_cookie }}"
    validate_certs:  "{{ ssl_verification }}"
  register: result
