#####################################################
# options:
#   policy_name:
#     description:
#       - The name of the NAT policy for which we should search
#       - If left blank all policies are returned
#     required: false
#     type: str

- set_fact:
    filter: "?filter=(name%20eq%20'{{ policy_name }}')"
  when: policy_name is defined

- set_fact:
    filter: ""
  when: policy_name is not defined

- name: SD - Get NAT Policy
  uri:
    url: "{{ space_api_uri }}/juniper/sd/policy-management/nat/policies{{ filter }}"
    method: GET
    return_content: yes
    headers:
      Accept: application/vnd.juniper.sd.policy-management.nat.policies+json;version=1;q=0.01
      Cookie: "{{ login.set_cookie }}"
    validate_certs:  "{{ ssl_verification }}"
  register: result
