---
- name: Space API Example - Get Jobs
  hosts: all
  connection: local
  gather_facts: no

  vars:
    space_api_uri: "https://{{ ansible_host }}:{{ space_api_port }}/api"
    space_api_login_uri : "space/user-management/login"
    ssl_verification: no

  tasks:
    - import_role:
        name: junos_space
        tasks_from: login

    - name: Get JOB List
      uri:
        url: "{{ space_api_uri }}/space/job-management/jobs/229410"
        method: GET
        follow_redirects: all
        return_content: yes
        headers:
          Accept: application/vnd.net.juniper.space.job-management.job+json;version=3
          Cookie: "{{ login.set_cookie }}"
        validate_certs:  "{{ ssl_verification }}"
      register: response
      until: response.json.job["job-state"] == "DONE"
      retries: 5
      delay: 10

    - name: print response
      debug:
        var: response.json
        verbosity: 1

    - import_role:
        name: junos_space
        tasks_from: logout
