---
- name: Space API Example - Get Devices
  hosts: all
  connection: local
  gather_facts: no

  vars:
    space_api_uri: "https://{{ ansible_host }}:{{ space_api_port }}/api"
    space_api_login_uri : "space/user-management/login"
    ssl_verification: no

  tasks:
    - import_role:
        name: junos_space
        tasks_from: login

    - import_role:
        name: junos_space
        tasks_from: get_devices

    - name: print results
      debug:
        var: result.json

    - import_role:
        name: junos_space
        tasks_from: logout
